//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushROMs.GenericEditor.PaletteEditor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class GotoSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GotoSettings defaultInstance = ((GotoSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GotoSettings())));
        
        public static GotoSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Address {
            get {
                return ((int)(this["Address"]));
            }
            set {
                this["Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PC")]
        public global::MushROMs.GenericEditor.PaletteEditor.GotoForm.GotoAddressFormats AddressMode {
            get {
                return ((global::MushROMs.GenericEditor.PaletteEditor.GotoForm.GotoAddressFormats)(this["AddressMode"]));
            }
            set {
                this["AddressMode"] = value;
            }
        }
    }
}
