//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushROMs.GenericEditor.PaletteEditor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class PaletteSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PaletteSettings defaultInstance = ((PaletteSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PaletteSettings())));
        
        public static PaletteSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LastFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LastFiles"]));
            }
            set {
                this["LastFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastOpenFilterIndex {
            get {
                return ((int)(this["LastOpenFilterIndex"]));
            }
            set {
                this["LastOpenFilterIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastSaveFilterIndex {
            get {
                return ((int)(this["LastSaveFilterIndex"]));
            }
            set {
                this["LastSaveFilterIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LastOpenPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LastOpenPaths"]));
            }
            set {
                this["LastOpenPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSavePath {
            get {
                return ((string)(this["LastSavePath"]));
            }
            set {
                this["LastSavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int DefaultViewWidth {
            get {
                return ((int)(this["DefaultViewWidth"]));
            }
            set {
                this["DefaultViewWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int DefaultViewHeight {
            get {
                return ((int)(this["DefaultViewHeight"]));
            }
            set {
                this["DefaultViewHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("248, 0, 248")]
        public global::System.Drawing.Color FallbackColor {
            get {
                return ((global::System.Drawing.Color)(this["FallbackColor"]));
            }
            set {
                this["FallbackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TPL")]
        public global::MushROMs.GenericEditor.PaletteEditor.PaletteDataFormats DefaultFormat {
            get {
                return ((global::MushROMs.GenericEditor.PaletteEditor.PaletteDataFormats)(this["DefaultFormat"]));
            }
            set {
                this["DefaultFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Zoom32x")]
        public global::MushROMs.GenericEditor.PaletteEditor.PaletteZoomScales DefaultZoom {
            get {
                return ((global::MushROMs.GenericEditor.PaletteEditor.PaletteZoomScales)(this["DefaultZoom"]));
            }
            set {
                this["DefaultZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Size1x")]
        public global::MushROMs.GenericEditor.PaletteEditor.PaletteBGSizes DefaultBGSize {
            get {
                return ((global::MushROMs.GenericEditor.PaletteEditor.PaletteBGSizes)(this["DefaultBGSize"]));
            }
            set {
                this["DefaultBGSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color DefaultBGColor1 {
            get {
                return ((global::System.Drawing.Color)(this["DefaultBGColor1"]));
            }
            set {
                this["DefaultBGColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color DefaultBGColor2 {
            get {
                return ((global::System.Drawing.Color)(this["DefaultBGColor2"]));
            }
            set {
                this["DefaultBGColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int DefaultDashLength1 {
            get {
                return ((int)(this["DefaultDashLength1"]));
            }
            set {
                this["DefaultDashLength1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color DefaultDashColor1 {
            get {
                return ((global::System.Drawing.Color)(this["DefaultDashColor1"]));
            }
            set {
                this["DefaultDashColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color DefaultDashColor2 {
            get {
                return ((global::System.Drawing.Color)(this["DefaultDashColor2"]));
            }
            set {
                this["DefaultDashColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstTime {
            get {
                return ((bool)(this["FirstTime"]));
            }
            set {
                this["FirstTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int DefaultDashLength2 {
            get {
                return ((int)(this["DefaultDashLength2"]));
            }
            set {
                this["DefaultDashLength2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxRecentFiles {
            get {
                return ((int)(this["MaxRecentFiles"]));
            }
            set {
                this["MaxRecentFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cross")]
        public global::System.Windows.Forms.Cursor DefaultCursor {
            get {
                return ((global::System.Windows.Forms.Cursor)(this["DefaultCursor"]));
            }
            set {
                this["DefaultCursor"] = value;
            }
        }
    }
}
