//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushROMs.GenericEditor.GFXEditor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class GFXSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GFXSettings defaultInstance = ((GFXSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GFXSettings())));
        
        public static GFXSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LstFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LstFiles"]));
            }
            set {
                this["LstFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastOpenFilterIndex {
            get {
                return ((int)(this["LastOpenFilterIndex"]));
            }
            set {
                this["LastOpenFilterIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastSaveFilterIndex {
            get {
                return ((int)(this["LastSaveFilterIndex"]));
            }
            set {
                this["LastSaveFilterIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LastOpenPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LastOpenPaths"]));
            }
            set {
                this["LastOpenPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSavePath {
            get {
                return ((string)(this["LastSavePath"]));
            }
            set {
                this["LastSavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int DefaultViewWidth {
            get {
                return ((int)(this["DefaultViewWidth"]));
            }
            set {
                this["DefaultViewWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int DefaultViewHeight {
            get {
                return ((int)(this["DefaultViewHeight"]));
            }
            set {
                this["DefaultViewHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SNES_4BPP")]
        public global::MushROMs.LunarCompress.GraphicsTypes DefaultBPPFormat {
            get {
                return ((global::MushROMs.LunarCompress.GraphicsTypes)(this["DefaultBPPFormat"]));
            }
            set {
                this["DefaultBPPFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LZ2")]
        public global::MushROMs.LunarCompress.CompressionFormats DefaultCompressFormat {
            get {
                return ((global::MushROMs.LunarCompress.CompressionFormats)(this["DefaultCompressFormat"]));
            }
            set {
                this["DefaultCompressFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Zoom2x")]
        public global::MushROMs.GenericEditor.GFXEditor.GFXZoomScales DefaultGFXZoom {
            get {
                return ((global::MushROMs.GenericEditor.GFXEditor.GFXZoomScales)(this["DefaultGFXZoom"]));
            }
            set {
                this["DefaultGFXZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int DefaultDashLength1 {
            get {
                return ((int)(this["DefaultDashLength1"]));
            }
            set {
                this["DefaultDashLength1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int DefaultDashLength2 {
            get {
                return ((int)(this["DefaultDashLength2"]));
            }
            set {
                this["DefaultDashLength2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color DefaultDashColor1 {
            get {
                return ((global::System.Drawing.Color)(this["DefaultDashColor1"]));
            }
            set {
                this["DefaultDashColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color DefaultDashColor2 {
            get {
                return ((global::System.Drawing.Color)(this["DefaultDashColor2"]));
            }
            set {
                this["DefaultDashColor2"] = value;
            }
        }
    }
}
